services:
  findex-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: findex-backend
    ports:
      - "5454:5454"
    environment:
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=5454
      - FLASK_ENV=production
      - FLASK_DEBUG=false
    env_file:
      - ./backend/.env
    volumes:
      # Mount the backend directory for development (optional)
      - ./backend:/app
    restart: unless-stopped
    networks:
      - findex-network

networks:
  findex-network:
    driver: bridge

