services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: findex-backend:latest
    container_name: findex-backend
    ports:
      - "5454:5454"
    environment:
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=5454
      - FLASK_ENV=production
      - FLASK_DEBUG=false
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
          - findex-network
          - nginxproxyman_network  

networks:
  findex-network:
    driver: bridge
  nginxproxyman_network:       
    external: true
    name: nginx-proxy-manager_nginxproxyman